#ifndef COMPUTERVISION_GLOBAL_H
#define COMPUTERVISION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPUTERVISION_LIBRARY)
#  define COMPUTERVISIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPUTERVISIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPUTERVISION_GLOBAL_H
